{% set name = "flatlatex" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flatlatex-{{ version }}.tar.gz
  sha256: 5170e1bcd4fccb52bdbdff300b14b68730483bc46f6a2a89f7ae2bb024e4d139

build:
  entry_points:
    - flatlatex=flatlatex.bin.flatlatex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - regex

test:
  imports:
    - flatlatex
  commands:
    - pip check
    - flatlatex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jb-leger/flatlatex
  summary: A LaTeX math converter to unicode text
  license: BSD-2-Clause
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jan-janssen
